### ISSUE TITLE
Requesting for Filipino Translation

### ISSUE THREAD

**Issue by vinzruzell** [rage8885/OpenSC2K#20]

**Comment by cursorial** [comment]
In the interest of not creating hundreds of issues around translations maybe we should create a parent task to encompass all languages?

**Comment by 8bitDave** [comment]
I offer myself to work on a Spanish translation when necessary.

**Comment by tmarie5** [comment]
How do I get pop Jr to open text codes for Me. Could You please help Me learn more about reading text and other codes. Thank You. For everything that a you have showed Me to use already. I had hub before they even opened the sites. My email isn't the same.

**Comment by DevNebulae** [comment]
I am offering myself to provide Dutch translations if the framework is there.

**Comment by cursorial** [comment]
I remember watching something once about a guy that came up with a good way
to handle open source translations.

Essentially, he created a CSV document that could be copied for each
language, in one column he had the English versions, and in the other he
had the translation.

We could store these CSV documents locally, and then when we add the option
in for language selection we simply pick the corresponding document from
the filesystem. This also helps to index which languages we have available
to the user.

It'll also be very easy for translators to do their job because they can
open the CSV in Microsoft Excel or Google Docs, or even just a plain text
editor and move down the list.

I'd be more than happy to implement this functionality or at least put a
framework in place since I think we'll probably need some form of game
state management before we start implementing menus and options dialogs.

The other thing to consider is that the menus are going to grow, so these
translations are likely to be living and breathing as the functionality
gets implemented. We'll have to find a way to keep older files updated.
Potentially a build step to sync up all existing language files.

**Comment by lcszulpo** [comment]
I offer myself to work in the Brazilian Portuguese translations

**Comment by 8bitDave** [comment]
Seeing what they have done with OpenTTD, for example, every language has its own txt file with the name of the string followed by a modificator and the string in that language, as follows:

NAME_OF_THE_STRING                 :{bold-or-whatever-modificator}This is the string itself in English

Seems a good approach, every language has its file, including English, and I assume the code refers to the NAME_OF_THE_STRING + the locale.txt as indicated on setup or .ini file.

My programming skills aren't enough to know how to implement this, but it could be easy to translate just picking up the English txt and doing the translation. And keeping an eye on that English file for the changes and add ons.

**Comment by DevNebulae** [comment]
I personally like the VSCode configuration files and the way MineCraft has done configuration management. The way MineCraft does it is with JSON files which its keys get reduced into a single string (e.g. `minecraft.brewing_stand.name: "Brewing Stand"). You could also introduce YAML files which make it less syntactically heavy.

**Comment by whphhg** [comment]
To extend on @DevNebulae locale naming suggestion. The first part of `en_US` is the `ISO 639-1 Code` [language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) and the second part is the `ISO 3166 Alpha-2 code` [country code](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes).

**Comment by vinzruzell** [comment]
Can I contribute filipino translation in here. Pls let me know. Thank you so.much.
