### ISSUE TITLE
Port to web

### ISSUE THREAD

**Issue by Luraktinus** [rage8885/OpenSC2K#38]
is it possible to play it without electron?

**Comment by rage8885** [comment]
Long term yes, short term some dependencies require native components.

**Comment by Luraktinus** [comment]
the thing is, electron is really hated by the community which is reasonable...

a huge amount of people wouldn't want to touch or try that game because of electron

**Comment by kokarn** [comment]
I'd just have to say that I don't agree with this at all.
Electron is great for this type of thing, among a lot of others.

AFAIK it's only growing with more and more people & companies using it to quickly build cross-platform solutions.

OFC it's not the most performant way but that's usually worth it in the end because of the much quicker development cycle.

**Comment by Daniel15** [comment]
@kokarn - A lot of the appeal of writing something in JavaScript is that you can run it in a browser without downloading or installing anything, and that it works on any OS without changes. Electron defeats that purpose :)

**Comment by kokarn** [comment]
It is indeed nice that some things run great in the browser. I'm not sure if this is one of those things tho. 

Take Discord or Slack as great examples of things that absolutely run great in a browser but most people still want to download the apps because they simply run better.

If it would be no extra work I would be all for ofc because more is better. Just wanted to add my 2c so it's just not one opinion :)

**Comment by rage8885** [comment]
I've been hard at work the last two weeks with a complete re-write using Phaser 3, webpack/eslint/babel, and a whole re-structure of the project. So far I've removed the dependency on native SQLite from the tile database. Re-working how city data is stored so I can remove the SQLite dependency entirely. Right now, I have it running outside of Electron (getting web pack, electron, phaser and my code all running together in harmony was two days of effort that went nowhere). 

Hopefully releasing soon, but I do have a few concerns about releasing a web-based version of the project - specifically around how to handle the original game graphics, sound and music. If it's hosted online, options are either hosting the assets with the engine (same thing we're doing now) which is not ideal, or forcing every user to upload their own assets every time they play (terrible user experience).

**Comment by Luraktinus** [comment]
wow, awesome OwO

**Comment by rage8885** [comment]
The rewrite has been pushed, still very much a WIP but it eliminates the Electron and SQLite dependencies entirely.
